name: Continuous Deployment to GCP [Windows]

on:
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Get the microservice version from README.md
        id: version
        run: |
          $PRP_PRD = Get-Content README.md | Select-String -Pattern '(?<=<!-- qsc-prd-start -->).*(?=<!-- qsc-prd-end -->)' | ForEach-Object { $_.Matches.Value }
          Write-Output "PRP_PRD=$PRP_PRD" >> $env:GITHUB_ENV

      - name: Build Image URL
        id: build_image_url
        run: |
          Write-Output "IMAGE_URL=${env:DOCKER_REGISTRY}/jtsato/${env:ARTIFACT_NAME}:${env:PRP_PRD}" >> $env:GITHUB_ENV

      - name: Set Environment Variables from GitHub Secrets
        env:
          IMAGE_URL: ${{ env.IMAGE_URL }}
          PRP_PRD: ${{ env.PRP_PRD }}
        run: |
          Write-Output "ARTIFACT=${env:IMAGE_URL}:${env:PRP_PRD}"
          Write-Output "TF_LOG=debug" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_PROJECT_ID=${env:PROJECT_ID}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_CLOUD_REGION=${env:CLOUD_REGION}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_ZONE=${env:ZONE}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_SERVICE_NAME=${env:SERVICE_NAME}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_IMAGE_URL=${env:IMAGE_URL}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_ASPNETCORE_ENVIRONMENT=${env:ASPNETCORE_ENVIRONMENT}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_ASPNETCORE_URLS=${env:ASPNETCORE_URLS}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_MONGODB_URL=${secrets.MONGODB_URL}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_MONGODB_DATABASE=${secrets.MONGODB_DATABASE}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_QUERY_STRUCTURE_COLLECTION_NAME=${secrets.QUERY_STRUCTURE_COLLECTION_NAME}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_QUERY_STRUCTURE_SEQUENCE_COLLECTION_NAME=${secrets.QUERY_STRUCTURE_SEQUENCE_COLLECTION_NAME}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_CLIENT_COLLECTION_NAME=${secrets.CLIENT_COLLECTION_NAME}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_CLIENT_SEQUENCE_COLLECTION_NAME=${secrets.CLIENT_SEQUENCE_COLLECTION_NAME}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_OPENAI_API_BASE_URL=${vars.OPENAI_API_BASE_URL}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_OPENAI_API_RETRY_ATTEMPTS=${vars.OPENAI_API_RETRY_ATTEMPTS}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_OPENAI_API_RETRY_DELAY_IN_SECONDS=${vars.OPENAI_API_RETRY_DELAY_IN_SECONDS}" >> $env:GITHUB_ENV
          Write-Output "TF_VAR_TZ=${env:TZ}" >> $env:GITHUB_ENV

      - name: Terraform Version
        run: terraform -version

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Terraform validate
        run: |
          terraform validate

      - name: Verify Terraform Providers
        run: |
          terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64

      - name: Create secrets.tfvars
        run: |
          Write-Output "project_id=\"$env:TF_VAR_PROJECT_ID\"" > secrets.tfvars
          Write-Output "cloud_region=\"$env:TF_VAR_CLOUD_REGION\"" >> secrets.tfvars
          Write-Output "zone=\"$env:TF_VAR_ZONE\"" >> secrets.tfvars
          Write-Output "service_name=\"$env:TF_VAR_SERVICE_NAME\"" >> secrets.tfvars
          Write-Output "image_url=\"$env:TF_VAR_IMAGE_URL\"" >> secrets.tfvars
          Write-Output "aspnetcore_environment=\"$env:TF_VAR_ASPNETCORE_ENVIRONMENT\"" >> secrets.tfvars
          Write-Output "aspnetcore_urls=[\"$env:TF_VAR_ASPNETCORE_URLS\"]" >> secrets.tfvars
          Write-Output "mongodb_url=\"$env:TF_VAR_MONGODB_URL\"" >> secrets.tfvars
          Write-Output "mongodb_database=\"$env:TF_VAR_MONGODB_DATABASE\"" >> secrets.tfvars
          Write-Output "query_structure_collection_name=\"$env:TF_VAR_QUERY_STRUCTURE_COLLECTION_NAME\"" >> secrets.tfvars
          Write-Output "query_structure_sequence_collection_name=\"$env:TF_VAR_QUERY_STRUCTURE_SEQUENCE_COLLECTION_NAME\"" >> secrets.tfvars
          Write-Output "client_collection_name=\"$env:TF_VAR_CLIENT_COLLECTION_NAME\"" >> secrets.tfvars
          Write-Output "client_sequence_collection_name=\"$env:TF_VAR_CLIENT_SEQUENCE_COLLECTION_NAME\"" >> secrets.tfvars
          Write-Output "openai_api_base_url=\"$env:TF_VAR_OPENAI_API_BASE_URL\"" >> secrets.tfvars
          Write-Output "openai_api_retry_attempts=\"$env:TF_VAR_OPENAI_API_RETRY_ATTEMPTS\"" >> secrets.tfvars
          Write-Output "openai_api_retry_delay_in_seconds=\"$env:TF_VAR_OPENAI_API_RETRY_DELAY_IN_SECONDS\"" >> secrets.tfvars
          Write-Output "tz=\"$env:TF_VAR_TZ\"" >> secrets.tfvars

      - name: Terraform Destroy
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform destroy -auto-approve -var-file=secrets.tfvars

      - name: Terraform Refresh
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform refresh -var-file=secrets.tfvars

      - name: Terraform State List
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform state list

      - name: Terraform Plan
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform plan -out=tfplan.out -var-file=secrets.tfvars

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve tfplan.out
